---
- name: Debug vault upload
  debug:
    msg: "Creating secret in Vault"

- set_fact:
    secret_sub_path: "cacerts"
  when: vault_identity.secret.type == 'ca'

- set_fact:
    secret_sub_path: "signcerts"
  when: vault_identity.secret.type == 'cert'

- set_fact:
    secret_sub_path: "keystore"
  when: vault_identity.secret.type == 'key'

- set_fact:
    secret_path: "{{ vault_identity.msp }}/{{ vault_identity.id }}/{{ vault_identity.secret.ca }}/{{ secret_sub_path }}"

- set_fact:
    vault_url: "{{ vault.url }}/{{ vault.path }}/{{ secret_path }}"

- name: Post create to Vault {{ vault_url }}
  uri:
    url: "{{ vault_url }}"
    method: POST
    body: "{ \"value\": \"{{ vault_identity.secret.value }}\" }"
    body_format: json
    headers:
      Content-Type: "application/json"
      X-Vault-Token: "{{ vault.token }}"
    status_code: 200, 204
  when: vault_identity.secret.value is defined

- name: Load the value of the key from file
  slurp:
    src: "{{ vault_identity.secret.path }}"
  register: secret_value
  when: vault_identity.secret.path is defined

- name: Post create to Vault {{ vault_url }}
  uri:
    url: "{{ vault_url }}"
    method: POST
    body: "{ \"value\": \"{{ secret_value.content }}\" }"
    body_format: json
    headers:
      Content-Type: "application/json"
      X-Vault-Token: "{{ vault.token }}"
    status_code: 200, 204
  when: vault_identity.secret.path is defined