---
- name: Check if "Swarm Mode" is enabled.
  shell: docker info
  changed_when: False
  register: docker_info
  
- set_fact:
    addvertised_address: "{{ ansible_default_ipv4.address + ':2377' }}" 

- name: Advertised address is
  debug: msg="{{ addvertised_address }}"

# - name: Init a new swarm with default parameters
#   docker_swarm:
#     state: present
#     advertise_addr: "{{ addvertised_address }}"
#   when: "docker_info.stdout.find('Swarm: active') == -1 and inventory_hostname == groups['{{target_machine}}'][0]"

- name: Init a new swarm with default parameters
  shell: 
    "docker swarm init --advertise-addr  {{ addvertised_address }}"
  when: "docker_info.stdout.find('Swarm: active') == -1 and inventory_hostname == groups['{{target_machine}}'][0]"