---
# Generate channel transaction configuration file requried to create a channel
- hosts: "{{ ca_machine }}"
  become: yes
  become_user: "{{ fabric_user_name | default('fabric') }}"

  roles:
    # - anchor-tx
    - anchor-tx-deploy
