---
# Start the temporary TLS root CA to issue TLS certs for the CA servers
- hosts: "{{ manager_machine }}"
  become: yes
  become_user: "{{ fabric_user_name | default('fabric') }}"
  vars:
    actionTag: stop
  roles:
    - role: ca-root-temp-boot