---
#### Bootstrap Fabric CA server

- hosts: "{{ ca_machine }}"
  become: yes
  become_user: "{{ fabric_user_name | default('fabric') }}"
  vars:
    actionTag: registerEnroll
  roles:
    - role: ca-root-temp-boot
