---
# Generate channel transaction configuration file requried to create a channel
# executes a peer channel create command in order to create the channel on the ordering service
- hosts: "{{ ca_machine }}"
  become: yes
  become_user: "{{ fabric_user_name | default('fabric') }}"

  roles:
    - setup
    - channel-tx
    - channel-tx-deploy