---
# Deploy HLF operations console
- hosts: "{{ target_machine }}"
  become: yes
  become_user: "{{ fabric_user_name | default('fabric') }}"
  tasks:
    - set_fact:
        deploy_fabric_console: true
    - include_role:
        name: config-fabric-operations-console
    - include_role:
        name: stacks
    - include_role:
        name: start
