---
# Register and enroll the described identities - peers and users
# Requires Setup of Fabric CA CLI and CA server up and running
- hosts: all
  become: yes
  become_user: "{{ server_user }}"

  roles:
   - register
   - enroll