---
- set_fact:
    ca: "{{ reg_ca }}"
    reg_msp: "{{ msp_def }}"

- set_fact:
    command_line: ""
    protocol: "http"
  when: reg_msp.tls_ca is defined and reg_msp.tls_ca == "yes"

- set_fact:
    path_tls: "{{ certs_folder }}/tls.{{ reg_msp.domain }}/msp/users/client/tls"

- set_fact:
    command_line: "--tls.certfiles {{ path_tls }}/ca.crt --tls.client.certfile {{ path_tls }}/cert.crt --tls.client.keyfile {{ path_tls }}/key.key"
    protocol: "https"
  when: reg_msp.tls_ca is undefined or reg_msp.tls_ca != "yes"

- name: Registers users for CA {{ ca.ca }}
  shell: >
    fabric-ca-client register -H {{ local_pki_folder }}/{{ msp_def.domain }}/fabric-ca/{{ ca.ca }}/clients/{{ ca.user }} -u {{ protocol }}://{{ ca.host }}:{{ ca.port }} --id.name {{ item.user }} --id.type {{ item.ou }} --id.secret password {{ command_line }}
  environment:
    PATH: "{{ fab_home_folder }}/current/bin"
  loop: "{{ ca.users }}"
  when: ca.users is defined