# calls the CA server to revoke the passed identity
# store the produced CRL on the file system using the passed path

- set_fact:
    ca: "{{ revoke_ca }}"

- set_fact:
    path_tls: "{{ certs_folder }}/tls.{{ ca.domain }}/msp/users/client/tls"

- set_fact:
    command_line: "--tls.certfiles {{  path_tls }}/ca.crt --tls.client.certfile {{ path_tls }}/cert.crt --tls.client.keyfile {{ path_tls }}/key.key"
    protocol: "https"

- name: Revoke the certs of the identity {{ identity }} for CA {{ ca.ca }}
  shell: >
    fabric-ca-client revoke -H {{ local_pki_folder }}/{{ ca.domain }}/fabric-ca/{{ ca.ca }}/clients/{{ ca.user }} -u {{ protocol }}://{{ ca.host }}:{{ ca.port }} -e {{ identity }} {{ command_line }} --gencrl
  environment:
    PATH: "{{ fab_home_folder }}/current/bin"