---
- name: Debug
  debug:
    msg: "###### Enroll the identities for all MSPs defined under msps list ###############"

- name: Enroll the users of all MSPs
  include_role:
    name: enroll-msp-identities
  vars:
    enrollment_msp: "{{ en_msp }}"
  loop: "{{ msps }}"
  loop_control:
    loop_var: en_msp
  when: en_msp.tls_ca is not defined or en_msp.tls_ca != 'yes'

- name: Debug
  debug:
    msg: "###### Enroll the identities for all MSPs finished ###############"