---

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "add docker repository"
  apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present
  when: ansible_distribution == "Ubuntu"

- name: "ensure old versions of docker are purged 1"
  apt: name=lxc-docker state=absent purge=yes
  when: ansible_distribution == "Ubuntu"

- name: "ensure old versions of docker are purged 2"
  apt: name=docker state=absent purge=yes
  when: ansible_distribution == "Ubuntu"

- name: "ensure old versions of docker are purged 3"
  apt: name=docker-engine state=absent purge=yes
  when: ansible_distribution == "Ubuntu"

- name: "ensure old versions of docker are purged 4"
  apt: name=docker.io state=absent purge=yes
  when: ansible_distribution == "Ubuntu"

# - name: Add Docker's public PGP key to the APT keyring
#   apt_key:
#     id: "{{ docker__apt_key_id }}"
#     url: "{{ docker__apt_key_url }}"
#   when: ansible_distribution == "Ubuntu"

- name: "install docker"
  apt: name=docker-ce=5:19.03.1* state=present update_cache=yes install_recommends=yes allow_unauthenticated=yes
  when: ansible_distribution == "Ubuntu"
  retries: 3
  delay: 20

#- name: "add docker group"
#  group: name=docker state=present

- name: "add docker user to docker group"
  user: name={{ fabric_user_name }} groups=docker append=yes

- name: "Generate daemon.json for Docker"
  template:
    src: "docker/daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    trim_blocks: no
    variable_start_string: "[["
    variable_end_string: "]]"

- name: "Restart Docker service"
  service: name=docker state=started

- name: "get docker info"
  shell: docker info
  register: docker_info
  changed_when: False

- name: Install Python pip
  apt:
    name: python-pip
    state: present

- name: Install Python pip3
  apt:
    name: python3-pip
    state: present

- name: Install docker python library
  pip:
    name: docker

- name: Install jsondiff
  pip:
    name: jsondiff

- name: Install pyyaml
  pip:
    name: pyyaml
